language: ruby
rvm:
  - 1.9.3
#  - 1.8.7
#  - jruby-18mode # JRuby in 1.8 mode
#  - jruby-19mode # JRuby in 1.9 mode
#  - rbx-18mode
#  - rbx-19mode

# Only build for commit and PR on the "develop" branch.
branches:
  only:
  - develop
env:
  global:
  - secure: fnIpPv97FR+I6QQhRJtMN0sotQhMQImEdDFZ+X7D7Mc6SMoFiAtrOhAP4uX/zau19FYPAlmT21H5ey6/mHUCCOur3QBdpFrvc2/u2ld1nebTSyIMoRZDPKX77WxqcO/jgJhM87yKZHHcUux/l3au29u4k5Fu8dEXpAFgCEIblzo=
script: rake travis
#after_success: rake rawler
